// <auto-generated />
using System;
using GIT_Backend.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GIT_Backend.Migrations
{
    [DbContext(typeof(GITDBContext))]
    partial class GITDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalysisRoute", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<short>("AnalyzerProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("analyzer_provider_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<short>("SourceProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("source_provider_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_analysis_route");

                    b.HasIndex("AnalyzerProviderId")
                        .HasDatabaseName("ix_analysis_route_analyzer_provider_id");

                    b.HasIndex("SourceProviderId", "AnalyzerProviderId")
                        .IsUnique()
                        .HasDatabaseName("UQ_analysis_route_source_analyzer");

                    b.ToTable("analysis_route", (string)null);
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalyzedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("ActualCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("actual_category_id");

                    b.Property<string>("AnalysisPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_payload_json");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<short>("AnalyzerProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("analyzer_provider_id");

                    b.Property<string>("BodySummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeywordJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("keyword_json");

                    b.Property<string>("LocationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("location_json");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<Guid>("RawContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_content_id");

                    b.Property<string>("TitleSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_summary");

                    b.HasKey("Id")
                        .HasName("pk_analyzed_contents");

                    b.HasIndex("ActualCategoryId")
                        .HasDatabaseName("ix_analyzed_contents_actual_category_id");

                    b.HasIndex("AnalyzerProviderId")
                        .HasDatabaseName("ix_analyzed_contents_analyzer_provider_id");

                    b.HasIndex("RawContentId")
                        .IsUnique()
                        .HasDatabaseName("ix_analyzed_contents_raw_content_id");

                    b.ToTable("analyzed_contents", (string)null);
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalyzerProvider", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("text")
                        .HasColumnName("endpoint_url");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_analyzer_provider");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_analyzer_provider_code");

                    b.ToTable("analyzer_provider", (string)null);
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.RawContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ExpectCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("expect_category_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json");

                    b.Property<short>("SourceProviderId")
                        .HasColumnType("smallint")
                        .HasColumnName("source_provider_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_raw_contents");

                    b.HasIndex("ContentId")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_contents_content_id");

                    b.HasIndex("ExpectCategoryId")
                        .HasDatabaseName("ix_raw_contents_expect_category_id");

                    b.HasIndex("SourceProviderId")
                        .HasDatabaseName("ix_raw_contents_source_provider_id");

                    b.HasIndex("SourceUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_raw_contents_source_url");

                    b.ToTable("raw_contents", (string)null);
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.SourceCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_source_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_source_category_code");

                    b.ToTable("source_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "culture",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "문화 관련 이슈",
                            Name = "문화"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "economy",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "경제 관련 이슈",
                            Name = "경제"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "welfare",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "복지 관련 이슈",
                            Name = "복지"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "transport",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "교통 관련 이슈",
                            Name = "교통"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "environment",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "환경 관련 이슈",
                            Name = "환경"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "housing",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "주택 관련 이슈",
                            Name = "주택"
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "safety",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "안전 관련 이슈",
                            Name = "안전"
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "administration",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "행정 관련 이슈",
                            Name = "행정"
                        });
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.SourceProvider", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<short>("ExpectCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("expect_category_id");

                    b.Property<int>("IntervalMin")
                        .HasColumnType("integer")
                        .HasColumnName("interval_min");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RequestDelayMs")
                        .HasColumnType("integer")
                        .HasColumnName("request_delay_ms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_source_provider");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_source_provider_code");

                    b.HasIndex("ExpectCategoryId")
                        .HasDatabaseName("ix_source_provider_expect_category_id");

                    b.ToTable("source_provider", (string)null);
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalysisRoute", b =>
                {
                    b.HasOne("GIT_Backend.Domain.Entity.AnalyzerProvider", "AnalyzerProvider")
                        .WithMany("AnalysisRoutes")
                        .HasForeignKey("AnalyzerProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_analyzer_provider_TO_analysis_route");

                    b.HasOne("GIT_Backend.Domain.Entity.SourceProvider", "SourceProvider")
                        .WithMany("AnalysisRoutes")
                        .HasForeignKey("SourceProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_source_provider_TO_analysis_route");

                    b.Navigation("AnalyzerProvider");

                    b.Navigation("SourceProvider");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalyzedContent", b =>
                {
                    b.HasOne("GIT_Backend.Domain.Entity.SourceCategory", "ActualCategory")
                        .WithMany("AnalyzedContents")
                        .HasForeignKey("ActualCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_source_category_TO_analyzed_contents");

                    b.HasOne("GIT_Backend.Domain.Entity.AnalyzerProvider", "AnalyzerProvider")
                        .WithMany("AnalyzedContents")
                        .HasForeignKey("AnalyzerProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_analyzer_provider_TO_analyzed_contents");

                    b.HasOne("GIT_Backend.Domain.Entity.RawContent", "RawContent")
                        .WithOne("AnalyzedContent")
                        .HasForeignKey("GIT_Backend.Domain.Entity.AnalyzedContent", "RawContentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_raw_contents_TO_analyzed_contents");

                    b.Navigation("ActualCategory");

                    b.Navigation("AnalyzerProvider");

                    b.Navigation("RawContent");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.RawContent", b =>
                {
                    b.HasOne("GIT_Backend.Domain.Entity.SourceCategory", "ExpectCategory")
                        .WithMany("RawContents")
                        .HasForeignKey("ExpectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_source_category_TO_raw_contents");

                    b.HasOne("GIT_Backend.Domain.Entity.SourceProvider", "SourceProvider")
                        .WithMany("RawContents")
                        .HasForeignKey("SourceProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_source_provider_TO_raw_contents");

                    b.Navigation("ExpectCategory");

                    b.Navigation("SourceProvider");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.SourceProvider", b =>
                {
                    b.HasOne("GIT_Backend.Domain.Entity.SourceCategory", "ExpectCategory")
                        .WithMany("SourceProviders")
                        .HasForeignKey("ExpectCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_source_category_TO_source_provider");

                    b.Navigation("ExpectCategory");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.AnalyzerProvider", b =>
                {
                    b.Navigation("AnalysisRoutes");

                    b.Navigation("AnalyzedContents");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.RawContent", b =>
                {
                    b.Navigation("AnalyzedContent");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.SourceCategory", b =>
                {
                    b.Navigation("AnalyzedContents");

                    b.Navigation("RawContents");

                    b.Navigation("SourceProviders");
                });

            modelBuilder.Entity("GIT_Backend.Domain.Entity.SourceProvider", b =>
                {
                    b.Navigation("AnalysisRoutes");

                    b.Navigation("RawContents");
                });
#pragma warning restore 612, 618
        }
    }
}
